version: '2'
services:
    stock-front:
        image: neilpeterson/stock-front
        ports:
            - "80:80"

    stock-back:
        image: neilpeterson/batch-stock-worker
        environment:
            - docker=http://0.0.0.0:2375/containers/
            
    stock-report:
        image: neilpeterson/batch-stock-report
