FROM tutum/apache-php

ENV connectionString DefaultEndpointsProtocol=https;AccountName=twoqueue;AccountKey=vCUrUB+0H0MAI/uozyqJ1NW0MFlIsCs31BJihIwIIxCEb7CXHR2luRb2fopNMPmvWFDrNZpqxCW5uKdJQjxVtA==;
ENV azurequeue twoqueue

RUN apt-get update && apt-get install git -y

RUN rm /app/* && mkdir /tmp-app

RUN git clone https://github.com/neilpeterson/container-stock-app.git /tmp-app && \
    cp -rf /rmp-app/php-stock-front/* /app \
    rm -rf /tmp-app

CMD /run.sh
