FROM python

ENV azurestoracct <replace>
ENV azurequeue <replace>
ENV azurequeuekey <replace>
ENV docker <replace>
ENV docker_image <replace>

RUN pip install requests
RUN pip install azure-storage
RUN mkdir /queue-worker && mkdir /tmp-app && \
    git clone https://github.com/neilpeterson/container-stock-app.git /tmp-app && \
    cp -rf /tmp-app/python-stock-back/* /queue-worker && \
    rm -rf /tmp-app

ENTRYPOINT ["python", "/queue-worker/queue-worker.py"]